from typing import Literal, TypeAlias

UnderfundingRationale: TypeAlias = Literal[
    "Critically low funding ratio",
    "Low funding ratio",
    "Funding ratio data incomplete",
    "Strong current funding ratio",
    "Declining funding trend",
    "Improving funding trend",
    "Worsening crisis",
    "At or above peer benchmark",
    "Very large impacted population",
    "Large impacted population",
    "Very large funding gap",
    "Large funding gap",
    "Material funding gap",
    "Data-limited assessment",
    "Not systematically underfunded",
    "Persistently weak pooled-fund coverage",
    "Weak pooled-fund coverage",
    "Severe education deprivation",
    "High education deprivation",
    "Severe food insecurity",
    "High food insecurity",
    "Severe health vulnerability",
    "High health vulnerability",
    "Severe sanitation stress",
    "High sanitation stress",
    "Severe protection risk",
    "High protection risk",
    "Severe sectoral stress",
    "High sectoral stress",
    "Broad multi-sector pressure",
    "Pressure across multiple sectors",
    "High average sector severity",
    "Lower sector severity",
    "No strong underfunding signals",
    "Mixed or incomplete risk evidence",
]


UNDERFUNDING_RATIONALES: tuple[UnderfundingRationale, ...] = (
    "Critically low funding ratio",
    "Low funding ratio",
    "Funding ratio data incomplete",
    "Strong current funding ratio",
    "Declining funding trend",
    "Improving funding trend",
    "Worsening crisis",
    "At or above peer benchmark",
    "Very large impacted population",
    "Large impacted population",
    "Very large funding gap",
    "Large funding gap",
    "Material funding gap",
    "Data-limited assessment",
    "Not systematically underfunded",
    "Persistently weak pooled-fund coverage",
    "Weak pooled-fund coverage",
    "Severe education deprivation",
    "High education deprivation",
    "Severe food insecurity",
    "High food insecurity",
    "Severe health vulnerability",
    "High health vulnerability",
    "Severe sanitation stress",
    "High sanitation stress",
    "Severe protection risk",
    "High protection risk",
    "Severe sectoral stress",
    "High sectoral stress",
    "Broad multi-sector pressure",
    "Pressure across multiple sectors",
    "High average sector severity",
    "Lower sector severity",
    "No strong underfunding signals",
    "Mixed or incomplete risk evidence",
)

UNDERFUNDING_RATIONALE_SET = frozenset(UNDERFUNDING_RATIONALES)
